### ISSUE TITLE
Black version change in pre-commit

### ISSUE THREAD

**Issue by jeffin07** [facebookresearch/theseus#142]
## 🐛 Bug

While `pre-commit  run --all-files` for the first time in a fresh install of theseus It gives an error for `black`

```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/root/.cache/pre-commit/repoadmyeab9/py_env-python3.7/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/root/.cache/pre-commit/repoadmyeab9/py_env-python3.7/lib/python3.7/site-packages/black/__init__.py", line 1423, in patched_main
    patch_click()
  File "/root/.cache/pre-commit/repoadmyeab9/py_env-python3.7/lib/python3.7/site-packages/black/__init__.py", line 1409, in patch_click
    from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/root/.cache/pre-commit/repoadmyeab9/py_env-python3.7/lib/python3.7/site-packages/click/__init__.py)


```

This is because of this [issue](https://github.com/psf/black/issues/2964)

A quick solution is to edit  `.pre-commit-config.yaml`

```
repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black

```
to 

```
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']

```
or

```
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black

```
## Steps to Reproduce

Clone a fresh copy and try to install pre-commit  and run `pre-commit run --all-files`

## Expected behavior

Successful pre-commit install
 

## System Info

- OS (e.g., Linux):Manjaro
- Python version:3.7.8

**Comment by mhmukadam** [comment]
Thanks for debugging this @jeffin07, can you submit a PR for this? cc @luisenp

**Comment by jeffin07** [comment]
@luisenp @mhmukadam Please review
